### ISSUE TITLE
Diagonal design elements break down at wider screens

### ISSUE THREAD

**Issue by danieltott** [code-newbies/codeland#82]
![image](https://user-images.githubusercontent.com/360261/131555589-bf74fffc-7c75-4f77-b083-87dd56fb7172.png)

These are created by making a pseudo-element, tilting it, stretching it, and then trying to position it: 

```css
 .section-card.attend:before {
   height: 120%;
    background: #E3EFEB;
    transform: rotate(2.5deg);
    left: -100px;
    top: -50px;
} 

.section-card:before {
    width: 150%;
    position: absolute;
    content: "";
}
```

Since the `left` and `top` values are in pixels, this will always break down at some point.

We could probably fix this by using `vw`, but I think there's probably a better way to do this simply using css gradients.
